apiVersion: v1
kind: ConfigMap
metadata:
  name: spinnaker-spinnaker-logback
  # namespace: spinnaker-stable
  labels:
{{ include "spinnaker.standard-labels" . | indent 4 }}  
data:
  logback.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration>
      <appender name="CONSOLE" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>%i.log</file>
        <rollingPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy">
          <fileNamePattern>%i.{yyyy-MM-dd_HH-mm}.log</fileNamePattern>
          <maxFileSize>1MB</maxFileSize>    
          <maxHistory>60</maxHistory>
          <totalSizeCap>1GB</totalSizeCap>
        </rollingPolicy>
        <encoder class="net.logstash.logback.encoder.LogstashEncoder" />
      </appender>  

      <root level="DEBUG">
        <appender-ref ref="CONSOLE" />
      </root>

    </configuration>